### ISSUE TITLE
[FEATURE] Create new reloading animation

### ISSUE THREAD

**Issue by ngu-khoi** [rau/content#170]
https://user-images.githubusercontent.com/85835085/180665790-8e64747a-12c6-4aa5-a99f-ebe3d13ad07a.mp4
- Current animation is default in the RefreshableScrollView Package.
- It is identical to Sidechat's current loading

[Exyte Loading Animation](https://github.com/exyte/ActivityIndicatorView)

https://user-images.githubusercontent.com/85835085/180665949-c4822757-528a-4466-a5f9-eede59995b06.mov

[Exyte Progress Indicator](https://github.com/exyte/ProgressIndicatorView)

[SwiftUI Loading Indicators](https://swiftpackageregistry.com/SwiftfulThinking/SwiftfulLoadingIndicators)

https://user-images.githubusercontent.com/85835085/180665913-9ae55692-1e05-4c6b-a1a4-90ac4cf33132.mov

**Comment by artemas-radik** [comment]
is this necessary for MVP?

**Comment by ngu-khoi** [comment]
> is this necessary for MVP?

u right this is low priority or closable
