### ISSUE TITLE
[REFACTOR] Switch all requests to alamofire

### ISSUE THREAD

**Issue by rau** [rau/content#200]
## What it currently is
URLSession

## What it should be
AF

**Comment by ngu-khoi** [comment]
- [ ] LoginViewModel
- [x] PostSettingsViewModel
- [ ] ProfileCommentBubbleViewModel
- [ ] ReportViewModel
- [ ] PostBubbleViewModel
- [ ] PhoneLoginViewModel
- [ ] VerificationViewModel
- [ ] FeedViewModel
- [ ] LeaderboardViewModel
- [ ] NewPostViewModel
- [ ] PostViewModel
- [ ] ProfileViewModel
