### ISSUE TITLE
[FEATURE] Verify that the device making an API request is an iOS device using DeviceCheck

### ISSUE THREAD

**Issue by rau** [rau/content#237]
## Acceptance criteria
https://developer.apple.com/documentation/devicecheck#overview

**Comment by ngu-khoi** [comment]
- AppAttest allows a request is a legitimate instance from the app

**Comment by ngu-khoi** [comment]
[How to do AppAttest](https://swiftrocks.com/app-attest-apple-protect-ios-jailbreak)
